<?
$PERM["admin"]["2"]="D";
$PERM["admin"]["6"]="D";
$PERM["admin"]["3"]="D";
$PERM["admin"]["4"]="D";
$PERM["admin"]["9"]="D";
$PERM["admin"]["10"]="D";
$PERM["admin"]["13"]="R";
$PERM["admin"]["11"]="D";
$PERM["admin"]["12"]="D";
$PERM["admin"]["7"]="R";
$PERM["admin"]["5"]="D";
$PERM["admin"]["8"]="R";
$PERM["admin"]["*"]="D";
$PERM["tools"]["5"]="T_8";
$PERM["rk.php"]["5"]="T_8";
$PERM["wizards"]["*"]="D";
?>