<?
use Bitrix\Main\Loader;
use Bitrix\Main\Config\Option;
use Bitrix\Main\Localization\Loc;
require ($_SERVER['DOCUMENT_ROOT'] . '/bitrix/header.php');
$APPLICATION->SetTitle( 'Заказы' );
Loc::loadMessages( __FILE__ );
if( Option::get( 'sotbit.b2bshop', 'ORDER_ORDERPHONE', 'Y' ) == 'Y' )
{
	$APPLICATION->IncludeComponent(
	"sotbit:order.phone", 
	"basket", 
	array(
		"DELIVERY_ID" => "3",
		"LOCAL_REDIRECT" => "/personal/order/success/",
		"OFFERS_PROPS" => array(
			0 => "=",
			1 => "{",
			2 => "u",
			3 => "n",
			4 => "s",
			5 => "e",
			6 => "r",
			7 => "i",
			8 => "a",
			9 => "l",
			10 => "i",
			11 => "z",
			12 => "e",
			13 => "(",
			14 => "O",
			15 => "p",
			16 => "t",
			17 => "i",
			18 => "o",
			19 => "n",
			20 => ":",
			21 => ":",
			22 => "g",
			23 => "e",
			24 => "t",
			25 => "(",
			26 => "\"",
			27 => "s",
			28 => "o",
			29 => "t",
			30 => "b",
			31 => "i",
			32 => "t",
			33 => ".",
			34 => "b",
			35 => "2",
			36 => "b",
			37 => "s",
			38 => "h",
			39 => "o",
			40 => "p",
			41 => "\"",
			42 => ",",
			43 => "\"",
			44 => "O",
			45 => "F",
			46 => "F",
			47 => "E",
			48 => "R",
			49 => "_",
			50 => "T",
			51 => "R",
			52 => "E",
			53 => "E",
			54 => "_",
			55 => "P",
			56 => "R",
			57 => "O",
			58 => "P",
			59 => "S",
			60 => "\"",
			61 => ",",
			62 => "\"",
			63 => "\"",
			64 => ")",
			65 => ")",
			66 => "}",
			67 => "",
		),
		"ORDER_ID" => "ORDER_ID",
		"ORDER_PROPS" => array(
		),
		"ORDER_TEL_PROP" => "3",
		"PAY_SYSTEM_ID" => "1",
		"PERSON_TYPE" => "1",
		"PRODUCT_ID" => "",
		"PRODUCT_PROPS" => array(
		),
		"PRODUCT_PROPS_VALUE" => "",
		"SELECT_USER" => "new",
		"SEND_EVENT" => "Y",
		"STATUS_ORDER" => "N",
		"SUBMIT_VALUE" => "Отправить заказ",
		"SUCCESS_TEXT" => "Ваш заказ оформлен",
		"TEL_MASK" => Option::get("sotbit.b2bshop","TEL_MASK","+7(999)999-99-99"),
		"TEXT_BOTTOM" => Loc::getMessage("MS_PHONE_TEXT_BOTTOM"),
		"TEXT_TOP" => "Введите Ваш телефон",
		"USER_GROUP" => "0",
		"COMPONENT_TEMPLATE" => "basket"
	),
	false
);
}




if( Option::get( 'sotbit.b2bshop', 'CART_IN_ORDER', '' ) == 'Y' )
{
	$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	"b2b_basket_order", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"COLUMNS_LIST" => array(
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "WEIGHT",
			3 => "DELETE",
			4 => "DELAY",
			5 => "TYPE",
			6 => "PRICE",
			7 => "QUANTITY",
		),
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"GIFTS_BLOCK_TITLE" => "",
		"GIFTS_CONVERT_CURRENCY" => "Y",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_HIDE_NOT_AVAILABLE" => "N",
		"GIFTS_MESS_BTN_BUY" => "",
		"GIFTS_MESS_BTN_DETAIL" => "",
		"GIFTS_PAGE_ELEMENT_COUNT" => "4",
		"GIFTS_PLACE" => "BOTTOM",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "prop",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "Y",
		"GIFTS_SHOW_IMAGE" => "Y",
		"GIFTS_SHOW_NAME" => "Y",
		"GIFTS_SHOW_OLD_PRICE" => "Y",
		"GIFTS_TEXT_LABEL_GIFT" => "",
		"HIDE_COUPON" => "N",
		"IBLOCK_ID" => Option::get("sotbit.b2bshop","IBLOCK_ID",""),
		"IBLOCK_TYPE" => "b2bs_catalog",
		"IMG_HEIGHT" => Option::get("sotbit.b2bshop","CART_IMG_HEIGHT",""),
		"IMG_WIDTH" => Option::get("sotbit.b2bshop","CART_IMG_WIDTH",""),
		"MANUFACTURER_ELEMENT_PROPS" => "",
		"MANUFACTURER_LIST_PROPS" => "",
		"MORE_PHOTO_OFFER_PROPS" => Option::get("sotbit.b2bshop","MORE_PHOTO_OFFER_PROPS",""),
		"MORE_PHOTO_PRODUCT_PROPS" => "",
		"OFFERS_PROPS" => "",
		"OFFER_COLOR_PROP" => "",
		"OFFER_TREE_PROPS" => array(
		),
		"PATH_TO_ORDER" => Option::get("sotbit.b2bshop","URL_PAGE_ORDER",""),
		"PICTURE_FROM_OFFER" => "N",
		"PRICE_VAT_SHOW_VALUE" => "Y",
		"QUANTITY_FLOAT" => "N",
		"SET_TITLE" => "N",
		"USE_GIFTS" => "Y",
		"USE_PREPAYMENT" => "N",
		"SHOW_VAT_PRICE" => "Y",
		"COMPONENT_TEMPLATE" => "b2b_basket_order",
		"COLUMNS_LIST_EXT" => array(
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
		),
		"SCHEME" => "#0065ff",
		"CORRECT_RATIO" => "Y",
		"AUTO_CALCULATION" => "Y",
		"COMPATIBLE_MODE" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"ADDITIONAL_PICT_PROP_4" => "-",
		"ADDITIONAL_PICT_PROP_5" => "-",
		"ADDITIONAL_PICT_PROP_11" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive"
	),
	false
);
}

$APPLICATION->IncludeComponent(
	"bitrix:sale.order.ajax", 
	"b2b_order_ajax", 
	array(
		"ALLOW_AUTO_REGISTER" => "Y",
		"ALLOW_NEW_PROFILE" => "Y",
		"BUYER_PERSONAL_TYPE" => unserialize(Option::get("sotbit.b2bshop","BUYER_PERSONAL_TYPE","a:0:{}")),
		"COMPONENT_TEMPLATE" => "b2b_order_ajax",
		"COUNT_DELIVERY_TAX" => "N",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"DELIVERY2PAY_SYSTEM" => "",
		"DELIVERY_NO_AJAX" => "Y",
		"DELIVERY_NO_SESSION" => "N",
		"DELIVERY_TO_PAYSYSTEM" => "d2p",
		"DISABLE_BASKET_REDIRECT" => "N",
		"ONLY_FULL_PAY_FROM_ACCOUNT" => "Y",
		"ORDER_ITEM_SHOW_COUNT" => Option::get("sotbit.b2bshop","ORDER_ITEM_SHOW_COUNT","5"),
		"PATH_TO_AUTH" => "/auth/",
		"PATH_TO_BASKET" => Option::get("sotbit.b2bshop","URL_CART",""),
		"PATH_TO_ORDER" => COption::GetOptionString("sotbit.b2bshop","URL_PAGE_ORDER",""),
		"PATH_TO_PAYMENT" => Option::get("sotbit.b2bshop","URL_PAYMENT",""),
		"PATH_TO_PERSONAL" => "/b2bcabinet/",
		"PAY_FROM_ACCOUNT" => "Y",
		"PRODUCT_COLUMNS" => "",
		"PROP_1" => "",
		"SEND_NEW_USER_NOTIFY" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_ACCOUNT_NUMBER" => "Y",
		"SHOW_PAYMENT_SERVICES_NAMES" => "Y",
		"SHOW_STORES_IMAGES" => "N",
		"TEMPLATE_LOCATION" => "popup",
		"USE_PREPAYMENT" => "N",
		"ALLOW_APPEND_ORDER" => "Y",
		"SHOW_NOT_CALCULATED_DELIVERIES" => "L",
		"SPOT_LOCATION_BY_GEOIP" => "Y",
		"SHOW_VAT_PRICE" => "Y",
		"COMPATIBLE_MODE" => "Y",
		"USE_PRELOAD" => "Y",
		"USER_CONSENT" => "N",
		"USER_CONSENT_ID" => "0",
		"USER_CONSENT_IS_CHECKED" => "Y",
		"USER_CONSENT_IS_LOADED" => "N",
		"ACTION_VARIABLE" => "soa-action",
		"EMPTY_BASKET_HINT_PATH" => "/",
		"USE_PHONE_NORMALIZATION" => "Y",
		"PRODUCT_COLUMNS_VISIBLE" => array(
			0 => "PREVIEW_PICTURE",
			1 => "PROPS",
		),
		"ADDITIONAL_PICT_PROP_4" => "-",
		"ADDITIONAL_PICT_PROP_5" => "-",
		"ADDITIONAL_PICT_PROP_11" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	),
	false
);

require ($_SERVER['DOCUMENT_ROOT'] . '/bitrix/footer.php');
?>